# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [3]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print(classes)

['Knee', 'Right', 'StandInit', 'HeadBack', 'Sit', 'Stand', 'Left', 'Back', 'Crouch', 'Belly', 'Frog']


In [4]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    with open(filename, 'rb') as pickled_file:
        data = pickle.load(pickled_file)
    target = [i] * len(data)
    return data, target

In [16]:
# load all the data
all_data = []
all_target = np.asarray([])
# YOUR CODE HERE
for i in range(len(classes)):
    data, target = load_pose_data(i)
    all_data.append(data)
    all_target = np.append(all_target, target)

all_data = np.concatenate(all_data, axis=0)
print(all_data.shape)
print(all_target.shape)
print('total number of data', len(all_data))

(222, 10)
(222,)
total number of data 222


In [17]:
# shuffle data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [18]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [27]:
# YOUR CODE HERE

clf.fit(all_data[:-100], all_target[:-100])

SVC(C=100.0, gamma=0.001)

### predicting

In [28]:
clf.predict(all_data[-1:]), all_target[-1:]

(array([4.]), array([10.]))

In [29]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [32]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[-100:]
predicted = clf.predict(all_data[-100:])
evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         2.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       1.00      0.44      0.62        18
         7.0       0.00      0.00      0.00        23
         8.0       0.00      0.00      0.00        30
         9.0       0.00      0.00      0.00        19
        10.0       0.00      0.00      0.00        10

    accuracy                           0.08       100
   macro avg       0.11      0.05      0.07       100
weighted avg       0.18      0.08      0.11       100


Confusion matrix:
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  4  0  6  8  0  0  0  0]
 [ 0 10  0 13  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0]
 [10  0  0  9  0  0  0  0  0]
 [ 0  0 10  0

/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarn

## 4. Evaluate on the test data

In [33]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[-100:]
predicted = clf.predict(all_data[-100:])
evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         2.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       1.00      0.44      0.62        18
         7.0       0.00      0.00      0.00        23
         8.0       0.00      0.00      0.00        30
         9.0       0.00      0.00      0.00        19
        10.0       0.00      0.00      0.00        10

    accuracy                           0.08       100
   macro avg       0.11      0.05      0.07       100
weighted avg       0.18      0.08      0.11       100


Confusion matrix:
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  4  0  6  8  0  0  0  0]
 [ 0 10  0 13  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0]
 [10  0  0  9  0  0  0  0  0]
 [ 0  0 10  0

/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarn

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [35]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))

Then, in the application we can load the trained classifier again.

In [37]:
clf2 = pickle.load(open(ROBOT_POSE_CLF, 'rb'))
clf2.predict(all_data[-1]), all_target[-1]

ValueError: Expected 2D array, got 1D array instead:
array=[-0.40953612 -0.19477606 -1.57997811  2.13682008 -0.40953612  0.28536606
 -1.66136408  2.13997221 -0.03316116  0.98611069].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.